seed_everything: 1555
trainer:
    precision: 32
    max_epochs: 100
    # fast_dev_run: True
    accelerator: 'cuda'
    devices: [0]
    logger:
        class_path: aim.pytorch_lightning.AimLogger
        init_args:
            experiment: 'deep_stpp'
            repo: .blackhole
    log_every_n_steps: 1
    callbacks:
        - class_path: ModelCheckpoint
          init_args:
            monitor: val_nll
model:
    class_path: models.lightning.deep_stpp.DeepSTPointProcess
    init_args:
        enc:
            class_path: models.lightning.deep_stpp.TransformerEncoder
            init_args:
                emb_dim: 128
                z_dim: 128
                dropout: 0
                num_head: 2
                seq_len: 20
                enc_n_layers: 3
                enc_hid_dim: 128
        w_dec:
            class_path: models.lightning.deep_stpp.MLPDecoder
            init_args:
                dec_hid_dim: 128
                dec_n_layers: 3
                softplus: true
        s_dec:
            class_path: models.lightning.deep_stpp.MLPDecoder
            init_args:
                dec_hid_dim: 128
                dec_n_layers: 3
                softplus: true
        b_dec:
            class_path: models.lightning.deep_stpp.MLPDecoder
            init_args:
                dec_hid_dim: 128
                dec_n_layers: 3
                softplus: false
        seq_len: 20
        s_min: 1.0e-4
        s_max: null
        b_max: 20
        lookahead: 1
        beta: 1.0e-3
        num_points: 20
        clip: 1.0
        constrain_b: false
        sample: false
        # Base and visualization params
        learning_rate: 0.0003
        step_size: 50
        gamma: 0.2
        nsteps: [101, 101, 101]
        round_time: true
        vis_type: ['interactive', 'static']
        start_idx: [0, 2]
        name: ComCat_25
data:
    class_path: data.lightning.sliding_window.SlidingWindowDataModule
    init_args:
        batch_size: 128
        num_workers: 8
        name: ComCat_25
        option: ready
catalog:
    Mcut: 2.5
    path: ../../Datasets/ComCat/ComCat_catalog.csv
    path_to_polygon: ../../Datasets/ComCat/california_shape.npy
    auxiliary_start: 1971-01-01 00:00:00
    train_nll_start: 1981-01-01 00:00:00
    val_nll_start: 1998-01-01 00:00:00
    test_nll_start: 2007-01-01 00:00:00
    test_nll_end: 2020-01-17 00:00:00
