seed_everything: 1554
trainer:
    precision: 32
    max_epochs: 100
    accelerator: cuda
    devices:
        - 0
    logger:
        class_path: aim.pytorch_lightning.AimLogger
        init_args:
            experiment: SCEDC_25_autoint_stpp_seed_1554
            repo: .blackhole
    log_every_n_steps: 1
    callbacks:
        -   class_path: ModelCheckpoint
            init_args:
                monitor: val_nll
model:
    class_path: models.lightning.autoint_stpp.AutoIntSTPointProcess
    init_args:
        n_prodnet: 10
        hidden_size: 128
        num_layers: 2
        activation: tanh
        learning_rate: 0.004
        step_size: 20
        gamma: 0.5
        nsteps:
            - 101
            - 101
            - 101
        round_time: true
        trunc: true
        vis_type:
            - interactive
            - static
        start_idx:
            - 0
            - 2
        name: SCEDC_25_autoint_stpp_seed_1554
data:
    class_path: data.lightning.sliding_window.SlidingWindowDataModule
    init_args:
        batch_size: 32
        num_workers: 8
        name: SCEDC_25_autoint_stpp_seed_1554
        option: ready
catalog:
    Mcut: 2.5
    path: ../../Datasets/SCEDC/SCEDC_catalog.csv
    path_to_polygon: ../../Datasets/SCEDC/SCEDC_shape.npy
    auxiliary_start: 1981-01-01 00:00:00
    train_nll_start: 1985-01-01 00:00:00
    val_nll_start: 2005-01-01 00:00:00
    test_nll_start: 2014-01-01 00:00:00
    test_nll_end: 2020-01-01 00:00:00
